# Generated by Django 4.0 on 2023-03-01 03:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteData', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500)),
                ('subtitle', models.CharField(blank=True, default='', max_length=2500, null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutCarouselImage',
        ),
        migrations.DeleteModel(
            name='ResultsIndividual',
        ),
        migrations.DeleteModel(
            name='ResultsSection',
        ),
    ]
