# Generated by Django 4.0 on 2023-03-11 16:15

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteData', '0003_resultimage_delete_aboutcarouselimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('name', models.CharField(max_length=250)),
                ('title', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('subtitle', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500)),
                ('subtitle', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ResultImage',
        ),
        migrations.AddField(
            model_name='resultsindividual',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteData.resultssection'),
        ),
    ]
