# Generated by Django 4.1.7 on 2023-03-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteData', '0004_resultsindividual_resultssection_delete_resultimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultssection',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='resultssection',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
