# Generated by Django 4.0 on 2023-03-12 10:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteData', '0005_alter_resultssection_options_resultssection_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsindividual',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
