# Generated by Django 4.0 on 2023-03-12 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteData', '0006_alter_resultsindividual_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultssection',
            options={'ordering': ['stream', 'order']},
        ),
        migrations.AddField(
            model_name='resultssection',
            name='stream',
            field=models.CharField(choices=[('JEE', 'JEE'), ('NEET', 'NEET')], default='JEE', max_length=30),
        ),
        migrations.AlterField(
            model_name='resultssection',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Order starts from 1.')]),
        ),
    ]
