# Generated by Django 4.0 on 2023-03-15 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteData', '0007_alter_resultssection_options_resultssection_stream_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultsindividual',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='resultsindividual',
            old_name='title',
            new_name='collegeName',
        ),
        migrations.RenameField(
            model_name='resultsindividual',
            old_name='subtitle',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='resultsindividual',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Order starts from 1.')]),
        ),
    ]
